#!/usr/bin/env bash

search_github() {
    local encoded_query=$(echo -n "$1" | jq -sRr @uri)
    curl -s "https://api.github.com/search/repositories?q=$encoded_query&sort=stars&order=desc" | jq -r '.items[0].html_url'
}

query=$(rofi -dmenu -p "GitHub Search:")
[ -z "$query" ] && exit 1

url=$(search_github "$query")
[ -z "$url" ] && { rofi -e "No results found."; exit 1; }

xdg-open "$url"
